name: Generate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 6"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE*"

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >>$GITHUB_ENV
          echo "CHINA_LIST=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf" >>$GITHUB_ENV
          echo "APPLE_LIST=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf" >>$GITHUB_ENV
          echo "GOOGLE_LIST=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf" >>$GITHUB_ENV
          echo "README_FILE=https://raw.githubusercontent.com/akiirui/clash-rule-china/main/README.md" >>$GITHUB_ENV
        shell: bash

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Download latest lists
        run: |
          echo "payload:" >china.yaml
          echo "payload:" >apple.yaml
          echo "payload:" >google.yaml
          curl -sSL "${CHINA_LIST}"  | cut -f 2 -d / | awk '{printf ("  - |+.%s|\n", $0)}' | sed "s/|/'/g" >>china.yaml
          curl -sSL "${APPLE_LIST}"  | cut -f 2 -d / | awk '{printf ("  - |+.%s|\n", $0)}' | sed "s/|/'/g" >>apple.yaml
          curl -sSL "${GOOGLE_LIST}" | cut -f 2 -d / | awk '{printf ("  - |+.%s|\n", $0)}' | sed "s/|/'/g" >>google.yaml
          curl -sSL "${README_FILE}" >>README

      - name: Push to release
        continue-on-error: true
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "3736910+akiirui@users.noreply.github.com"
          git commit -am "${{ env.RELEASE_NAME }}"
          git push origin release

      - name: Generate sha512sum
        run: |
          sha512sum *.yaml > sha512sum

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.yaml,sha512sum"
          body: ${{ env.RELEASE_NAME }}
          name: ${{ env.RELEASE_NAME }}
          commit: release
          tag: ${{ env.RELEASE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
